import type { Language, Level } from '../App';

export interface ProblemData {
  title: string;
  description: string;
  expectedOutput: string;
}

type ProblemsDatabase = {
  [key in Language]: {
    [key in Level]: ProblemData[];
  };
};

const generateProblems = (language: Language, level: Level): ProblemData[] => {
  const problems: ProblemData[] = [];
  
  // Language-specific problems
  if (language === 'Python') {
    const pythonTemplates = {
      easy: [
        { title: 'Print Statement', description: 'Write a program to print "Hello Python"', expectedOutput: 'Hello Python' },
        { title: 'List Creation', description: 'Create a list with numbers 1 to 5 and print it', expectedOutput: '[1, 2, 3, 4, 5]' },
        { title: 'String Length', description: 'Find length of string "Python"', expectedOutput: '6' },
        { title: 'List Append', description: 'Create list [1,2,3] and append 4', expectedOutput: '[1, 2, 3, 4]' },
        { title: 'Dictionary Basics', description: 'Create dict with key "name" and value "Python"', expectedOutput: '{"name": "Python"}' },
        { title: 'Range Function', description: 'Print numbers from 1 to 5 using range', expectedOutput: '1 2 3 4 5' },
        { title: 'String Concatenation', description: 'Concatenate "Hello" and "World"', expectedOutput: 'HelloWorld' },
        { title: 'Type Conversion', description: 'Convert string "123" to integer', expectedOutput: '123' },
        { title: 'Boolean Check', description: 'Check if 5 > 3', expectedOutput: 'True' },
        { title: 'List Indexing', description: 'Get first element of [10,20,30]', expectedOutput: '10' },
        { title: 'String Upper', description: 'Convert "python" to uppercase', expectedOutput: 'PYTHON' },
        { title: 'List Length', description: 'Find length of list [1,2,3,4,5]', expectedOutput: '5' },
        { title: 'Tuple Creation', description: 'Create tuple with values (1,2,3)', expectedOutput: '(1, 2, 3)' },
        { title: 'String Split', description: 'Split "a,b,c" by comma', expectedOutput: '["a", "b", "c"]' },
        { title: 'Min Function', description: 'Find minimum of [5,2,8,1]', expectedOutput: '1' },
        { title: 'Max Function', description: 'Find maximum of [5,2,8,1]', expectedOutput: '8' },
        { title: 'List Sum', description: 'Find sum of [1,2,3,4,5]', expectedOutput: '15' },
        { title: 'String Replace', description: 'Replace "a" with "b" in "banana"', expectedOutput: 'bbnbnb' },
        { title: 'Set Creation', description: 'Create set with {1,2,3}', expectedOutput: '{1, 2, 3}' },
        { title: 'List Reverse', description: 'Reverse list [1,2,3,4,5]', expectedOutput: '[5, 4, 3, 2, 1]' },
      ],
      medium: [
        { title: 'List Comprehension', description: 'Create list of squares from 1 to 5', expectedOutput: '[1, 4, 9, 16, 25]' },
        { title: 'Lambda Function', description: 'Create lambda to add 10 to a number', expectedOutput: 'Lambda created' },
        { title: 'Map Function', description: 'Square all numbers in [1,2,3,4]', expectedOutput: '[1, 4, 9, 16]' },
        { title: 'Filter Function', description: 'Filter even numbers from [1,2,3,4,5,6]', expectedOutput: '[2, 4, 6]' },
        { title: 'Dictionary Methods', description: 'Get all keys from dict', expectedOutput: 'Keys retrieved' },
        { title: 'File Reading', description: 'Read content from file', expectedOutput: 'File content' },
        { title: 'Exception Handling', description: 'Handle division by zero', expectedOutput: 'Exception handled' },
        { title: 'Class Definition', description: 'Create class Person with name attribute', expectedOutput: 'Class created' },
        { title: 'Inheritance', description: 'Create child class from parent', expectedOutput: 'Inheritance implemented' },
        { title: 'Decorators', description: 'Create simple decorator function', expectedOutput: 'Decorator applied' },
        { title: 'Generators', description: 'Create generator for fibonacci', expectedOutput: 'Generator created' },
        { title: 'Set Operations', description: 'Find union of two sets', expectedOutput: 'Union found' },
        { title: 'String Formatting', description: 'Format string with f-strings', expectedOutput: 'Formatted string' },
        { title: 'List Slicing', description: 'Get elements from index 2 to 5', expectedOutput: 'Slice obtained' },
        { title: 'Dictionary Comprehension', description: 'Create dict from two lists', expectedOutput: 'Dict created' },
        { title: 'Nested Lists', description: 'Access element in 2D list', expectedOutput: 'Element accessed' },
        { title: 'Enumerate Function', description: 'Loop with index and value', expectedOutput: 'Enumeration complete' },
        { title: 'Zip Function', description: 'Combine two lists', expectedOutput: 'Lists zipped' },
        { title: 'Module Import', description: 'Import and use math module', expectedOutput: 'Module imported' },
        { title: 'Regular Expressions', description: 'Match pattern in string', expectedOutput: 'Pattern matched' },
      ],
      hard: [
        { title: 'Multithreading', description: 'Create and run multiple threads', expectedOutput: 'Threads executed' },
        { title: 'Asyncio', description: 'Implement async/await pattern', expectedOutput: 'Async completed' },
        { title: 'Context Manager', description: 'Create custom context manager', expectedOutput: 'Context manager created' },
        { title: 'Metaclasses', description: 'Define and use metaclass', expectedOutput: 'Metaclass defined' },
        { title: 'Property Decorators', description: 'Use @property decorator', expectedOutput: 'Property created' },
        { title: 'Abstract Classes', description: 'Create abstract base class', expectedOutput: 'ABC created' },
        { title: 'Iterator Protocol', description: 'Implement __iter__ and __next__', expectedOutput: 'Iterator created' },
        { title: 'Custom Exceptions', description: 'Define custom exception class', expectedOutput: 'Exception defined' },
        { title: 'Pickle Module', description: 'Serialize and deserialize object', expectedOutput: 'Object pickled' },
        { title: 'JSON Parsing', description: 'Parse complex JSON structure', expectedOutput: 'JSON parsed' },
        { title: 'Database Connection', description: 'Connect to SQLite database', expectedOutput: 'DB connected' },
        { title: 'Web Scraping', description: 'Extract data from HTML', expectedOutput: 'Data scraped' },
        { title: 'API Request', description: 'Make HTTP GET request', expectedOutput: 'Request sent' },
        { title: 'DataFrame Operations', description: 'Manipulate pandas DataFrame', expectedOutput: 'DataFrame processed' },
        { title: 'Numpy Arrays', description: 'Perform matrix operations', expectedOutput: 'Matrix calculated' },
        { title: 'File Compression', description: 'Compress file using zipfile', expectedOutput: 'File compressed' },
        { title: 'Memory Profiling', description: 'Profile memory usage', expectedOutput: 'Memory profiled' },
        { title: 'Logging System', description: 'Implement logging framework', expectedOutput: 'Logs created' },
        { title: 'Unit Testing', description: 'Write unit tests with unittest', expectedOutput: 'Tests passed' },
        { title: 'Socket Programming', description: 'Create TCP socket connection', expectedOutput: 'Socket created' },
      ],
      extreme: [
        { title: 'Neural Network', description: 'Build simple neural network', expectedOutput: 'NN trained' },
        { title: 'Machine Learning', description: 'Train classification model', expectedOutput: 'Model trained' },
        { title: 'Deep Learning', description: 'Implement CNN architecture', expectedOutput: 'CNN built' },
        { title: 'Natural Language', description: 'Process text with NLP', expectedOutput: 'Text processed' },
        { title: 'Computer Vision', description: 'Detect objects in image', expectedOutput: 'Objects detected' },
        { title: 'Recommendation System', description: 'Build recommendation engine', expectedOutput: 'Recommendations made' },
        { title: 'Time Series', description: 'Forecast time series data', expectedOutput: 'Forecast generated' },
        { title: 'Clustering Algorithm', description: 'Implement K-means clustering', expectedOutput: 'Clusters formed' },
        { title: 'Decision Trees', description: 'Build decision tree classifier', expectedOutput: 'Tree built' },
        { title: 'Random Forest', description: 'Implement random forest', expectedOutput: 'Forest created' },
        { title: 'SVM Implementation', description: 'Build SVM classifier', expectedOutput: 'SVM trained' },
        { title: 'Gradient Descent', description: 'Implement gradient descent', expectedOutput: 'Optimized' },
        { title: 'Backpropagation', description: 'Implement backprop algorithm', expectedOutput: 'Backprop done' },
        { title: 'GAN Network', description: 'Build generative adversarial network', expectedOutput: 'GAN trained' },
        { title: 'Transfer Learning', description: 'Use pre-trained model', expectedOutput: 'Transfer complete' },
        { title: 'Reinforcement Learning', description: 'Implement Q-learning', expectedOutput: 'Agent trained' },
        { title: 'LSTM Network', description: 'Build LSTM for sequences', expectedOutput: 'LSTM trained' },
        { title: 'Attention Mechanism', description: 'Implement attention layer', expectedOutput: 'Attention applied' },
        { title: 'Transformer Model', description: 'Build transformer architecture', expectedOutput: 'Transformer built' },
        { title: 'AutoEncoder', description: 'Implement autoencoder', expectedOutput: 'Encoder trained' },
      ],
    };
    return pythonTemplates[level];
  }

  if (language === 'MySQL') {
    const mysqlTemplates = {
      easy: [
        { title: 'Select All', description: 'SELECT all records from users table', expectedOutput: 'All records selected' },
        { title: 'Insert Record', description: 'INSERT a new user into users table', expectedOutput: '1 row inserted' },
        { title: 'Update Record', description: 'UPDATE user name where id=1', expectedOutput: '1 row updated' },
        { title: 'Delete Record', description: 'DELETE user where id=5', expectedOutput: '1 row deleted' },
        { title: 'Where Clause', description: 'SELECT users where age > 18', expectedOutput: 'Filtered records' },
        { title: 'Order By', description: 'SELECT users ORDER BY name', expectedOutput: 'Sorted records' },
        { title: 'Count Records', description: 'COUNT total number of users', expectedOutput: 'Count: 10' },
        { title: 'Distinct Values', description: 'SELECT DISTINCT cities', expectedOutput: 'Unique cities' },
        { title: 'Limit Clause', description: 'SELECT first 5 users', expectedOutput: '5 records' },
        { title: 'Like Operator', description: 'SELECT users where name LIKE "A%"', expectedOutput: 'Matching records' },
        { title: 'Between Operator', description: 'SELECT users where age BETWEEN 20 AND 30', expectedOutput: 'Age range records' },
        { title: 'In Operator', description: 'SELECT users where city IN (NYC, LA)', expectedOutput: 'City records' },
        { title: 'Is Null', description: 'SELECT users where email IS NULL', expectedOutput: 'Null records' },
        { title: 'Max Function', description: 'Find MAX age from users', expectedOutput: 'Max: 65' },
        { title: 'Min Function', description: 'Find MIN age from users', expectedOutput: 'Min: 18' },
        { title: 'Avg Function', description: 'Calculate AVG age', expectedOutput: 'Avg: 35.5' },
        { title: 'Sum Function', description: 'Calculate SUM of salaries', expectedOutput: 'Sum: 250000' },
        { title: 'Group By', description: 'GROUP BY city and count users', expectedOutput: 'Grouped results' },
        { title: 'Having Clause', description: 'Use HAVING with GROUP BY', expectedOutput: 'Filtered groups' },
        { title: 'Concat Function', description: 'CONCAT first_name and last_name', expectedOutput: 'Full names' },
      ],
      medium: [
        { title: 'Inner Join', description: 'Join users and orders tables', expectedOutput: 'Joined records' },
        { title: 'Left Join', description: 'LEFT JOIN users with orders', expectedOutput: 'All users with orders' },
        { title: 'Right Join', description: 'RIGHT JOIN orders with users', expectedOutput: 'All orders with users' },
        { title: 'Self Join', description: 'Join table to itself', expectedOutput: 'Self-joined records' },
        { title: 'Subquery', description: 'Use subquery in WHERE clause', expectedOutput: 'Subquery results' },
        { title: 'Union Operator', description: 'Combine two SELECT statements', expectedOutput: 'Combined results' },
        { title: 'Case Statement', description: 'Use CASE for conditional logic', expectedOutput: 'Conditional output' },
        { title: 'View Creation', description: 'CREATE VIEW for frequent query', expectedOutput: 'View created' },
        { title: 'Index Creation', description: 'CREATE INDEX on email column', expectedOutput: 'Index created' },
        { title: 'Alter Table', description: 'ALTER TABLE to add column', expectedOutput: 'Table altered' },
        { title: 'Foreign Key', description: 'Add FOREIGN KEY constraint', expectedOutput: 'FK added' },
        { title: 'Unique Constraint', description: 'Add UNIQUE constraint', expectedOutput: 'Constraint added' },
        { title: 'Date Functions', description: 'Use NOW() and DATE functions', expectedOutput: 'Date calculated' },
        { title: 'String Functions', description: 'Use UPPER, LOWER, SUBSTRING', expectedOutput: 'String modified' },
        { title: 'Aggregate Functions', description: 'Combine multiple aggregates', expectedOutput: 'Aggregates calculated' },
        { title: 'Exists Operator', description: 'Use EXISTS in subquery', expectedOutput: 'Exists check done' },
        { title: 'Truncate Table', description: 'TRUNCATE table data', expectedOutput: 'Table truncated' },
        { title: 'Transaction Begin', description: 'Start transaction', expectedOutput: 'Transaction started' },
        { title: 'Commit Transaction', description: 'COMMIT changes', expectedOutput: 'Changes committed' },
        { title: 'Rollback Transaction', description: 'ROLLBACK changes', expectedOutput: 'Changes rolled back' },
      ],
      hard: [
        { title: 'Stored Procedure', description: 'CREATE stored procedure', expectedOutput: 'Procedure created' },
        { title: 'Triggers', description: 'CREATE trigger for audit', expectedOutput: 'Trigger created' },
        { title: 'Cursors', description: 'Use cursor to iterate records', expectedOutput: 'Cursor executed' },
        { title: 'Window Functions', description: 'Use ROW_NUMBER() function', expectedOutput: 'Window function applied' },
        { title: 'CTEs', description: 'Common Table Expressions', expectedOutput: 'CTE executed' },
        { title: 'Pivot Table', description: 'Create pivot table', expectedOutput: 'Pivoted data' },
        { title: 'Recursive Query', description: 'Use recursive CTE', expectedOutput: 'Recursive query done' },
        { title: 'Partitioning', description: 'Partition table by date', expectedOutput: 'Table partitioned' },
        { title: 'Full Text Search', description: 'Implement full-text search', expectedOutput: 'Search results' },
        { title: 'JSON Functions', description: 'Query JSON data type', expectedOutput: 'JSON queried' },
        { title: 'Ranking Functions', description: 'Use RANK() and DENSE_RANK()', expectedOutput: 'Rankings calculated' },
        { title: 'Lead and Lag', description: 'Use LEAD() and LAG() functions', expectedOutput: 'Lead/Lag applied' },
        { title: 'Dynamic SQL', description: 'Execute dynamic SQL statement', expectedOutput: 'Dynamic SQL run' },
        { title: 'Performance Tuning', description: 'Optimize slow query', expectedOutput: 'Query optimized' },
        { title: 'Query Plan', description: 'Analyze EXPLAIN plan', expectedOutput: 'Plan analyzed' },
        { title: 'Backup Database', description: 'Create database backup', expectedOutput: 'Backup created' },
        { title: 'Restore Database', description: 'Restore from backup', expectedOutput: 'DB restored' },
        { title: 'User Management', description: 'CREATE USER and GRANT privileges', expectedOutput: 'User created' },
        { title: 'Database Replication', description: 'Setup master-slave replication', expectedOutput: 'Replication setup' },
        { title: 'Query Cache', description: 'Configure query caching', expectedOutput: 'Cache configured' },
      ],
      extreme: [
        { title: 'Sharding Strategy', description: 'Implement database sharding', expectedOutput: 'Sharding implemented' },
        { title: 'Load Balancing', description: 'Setup database load balancer', expectedOutput: 'Load balanced' },
        { title: 'High Availability', description: 'Configure HA cluster', expectedOutput: 'HA configured' },
        { title: 'Data Warehousing', description: 'Design data warehouse schema', expectedOutput: 'Warehouse designed' },
        { title: 'ETL Pipeline', description: 'Build ETL process', expectedOutput: 'ETL pipeline built' },
        { title: 'OLAP Cubes', description: 'Create OLAP cube', expectedOutput: 'Cube created' },
        { title: 'Time Travel Query', description: 'Query historical data', expectedOutput: 'Historical data retrieved' },
        { title: 'Change Data Capture', description: 'Implement CDC', expectedOutput: 'CDC implemented' },
        { title: 'Data Encryption', description: 'Encrypt sensitive columns', expectedOutput: 'Data encrypted' },
        { title: 'Audit Logging', description: 'Comprehensive audit system', expectedOutput: 'Audit system active' },
        { title: 'Connection Pooling', description: 'Optimize connection pool', expectedOutput: 'Pool optimized' },
        { title: 'Deadlock Resolution', description: 'Handle and resolve deadlocks', expectedOutput: 'Deadlock resolved' },
        { title: 'Schema Migration', description: 'Manage schema versions', expectedOutput: 'Migration complete' },
        { title: 'Multi-tenant DB', description: 'Design multi-tenant architecture', expectedOutput: 'Multi-tenant setup' },
        { title: 'Geo-replication', description: 'Setup geographic replication', expectedOutput: 'Geo-replication active' },
        { title: 'Database Monitoring', description: 'Implement monitoring system', expectedOutput: 'Monitoring setup' },
        { title: 'Query Governor', description: 'Limit query execution time', expectedOutput: 'Governor configured' },
        { title: 'Materialized Views', description: 'Create and refresh mat views', expectedOutput: 'Mat views created' },
        { title: 'Database Firewall', description: 'Configure DB firewall rules', expectedOutput: 'Firewall configured' },
        { title: 'Disaster Recovery', description: 'Design DR strategy', expectedOutput: 'DR plan implemented' },
      ],
    };
    return mysqlTemplates[level];
  }

  if (language === 'CSS') {
    const cssTemplates = {
      easy: [
        { title: 'Color Property', description: 'Set text color to red', expectedOutput: 'color: red;' },
        { title: 'Background Color', description: 'Set background to blue', expectedOutput: 'background-color: blue;' },
        { title: 'Font Size', description: 'Set font size to 16px', expectedOutput: 'font-size: 16px;' },
        { title: 'Font Family', description: 'Set font to Arial', expectedOutput: 'font-family: Arial;' },
        { title: 'Text Align', description: 'Center align text', expectedOutput: 'text-align: center;' },
        { title: 'Margin', description: 'Set margin to 10px', expectedOutput: 'margin: 10px;' },
        { title: 'Padding', description: 'Set padding to 20px', expectedOutput: 'padding: 20px;' },
        { title: 'Border', description: 'Add 1px solid black border', expectedOutput: 'border: 1px solid black;' },
        { title: 'Width Property', description: 'Set width to 100px', expectedOutput: 'width: 100px;' },
        { title: 'Height Property', description: 'Set height to 50px', expectedOutput: 'height: 50px;' },
        { title: 'Display Block', description: 'Set display to block', expectedOutput: 'display: block;' },
        { title: 'Display Inline', description: 'Set display to inline', expectedOutput: 'display: inline;' },
        { title: 'Text Decoration', description: 'Underline text', expectedOutput: 'text-decoration: underline;' },
        { title: 'Font Weight', description: 'Set font weight to bold', expectedOutput: 'font-weight: bold;' },
        { title: 'Line Height', description: 'Set line height to 1.5', expectedOutput: 'line-height: 1.5;' },
        { title: 'Border Radius', description: 'Set border radius to 5px', expectedOutput: 'border-radius: 5px;' },
        { title: 'Opacity', description: 'Set opacity to 0.5', expectedOutput: 'opacity: 0.5;' },
        { title: 'Cursor Pointer', description: 'Set cursor to pointer', expectedOutput: 'cursor: pointer;' },
        { title: 'List Style', description: 'Remove list bullets', expectedOutput: 'list-style: none;' },
        { title: 'Overflow Hidden', description: 'Hide overflow content', expectedOutput: 'overflow: hidden;' },
      ],
      medium: [
        { title: 'Flexbox Container', description: 'Create flex container', expectedOutput: 'display: flex;' },
        { title: 'Justify Content', description: 'Center items with flexbox', expectedOutput: 'justify-content: center;' },
        { title: 'Align Items', description: 'Vertically align items', expectedOutput: 'align-items: center;' },
        { title: 'Grid Layout', description: 'Create CSS grid', expectedOutput: 'display: grid;' },
        { title: 'Grid Template', description: 'Define grid columns', expectedOutput: 'grid-template-columns: 1fr 1fr;' },
        { title: 'Position Relative', description: 'Set relative positioning', expectedOutput: 'position: relative;' },
        { title: 'Position Absolute', description: 'Set absolute positioning', expectedOutput: 'position: absolute;' },
        { title: 'Z-Index', description: 'Set stacking order', expectedOutput: 'z-index: 10;' },
        { title: 'Box Shadow', description: 'Add shadow to element', expectedOutput: 'box-shadow: 2px 2px 5px rgba(0,0,0,0.3);' },
        { title: 'Text Shadow', description: 'Add shadow to text', expectedOutput: 'text-shadow: 1px 1px 2px black;' },
        { title: 'Transform Rotate', description: 'Rotate element 45deg', expectedOutput: 'transform: rotate(45deg);' },
        { title: 'Transform Scale', description: 'Scale element to 1.5', expectedOutput: 'transform: scale(1.5);' },
        { title: 'Transition', description: 'Add transition effect', expectedOutput: 'transition: all 0.3s ease;' },
        { title: 'Hover Effect', description: 'Change color on hover', expectedOutput: ':hover { color: blue; }' },
        { title: 'Media Query', description: 'Responsive design for mobile', expectedOutput: '@media (max-width: 768px)' },
        { title: 'Pseudo Elements', description: 'Use ::before pseudo element', expectedOutput: '::before { content: ""; }' },
        { title: 'Gradient Background', description: 'Linear gradient background', expectedOutput: 'background: linear-gradient();' },
        { title: 'Multiple Columns', description: 'Create column layout', expectedOutput: 'column-count: 3;' },
        { title: 'Object Fit', description: 'Fit image in container', expectedOutput: 'object-fit: cover;' },
        { title: 'Custom Properties', description: 'Define CSS variable', expectedOutput: '--main-color: #333;' },
      ],
      hard: [
        { title: 'Animation Keyframes', description: 'Create @keyframes animation', expectedOutput: '@keyframes slide' },
        { title: 'Complex Animation', description: 'Multi-step animation', expectedOutput: 'animation: name 2s ease-in-out;' },
        { title: 'CSS Grid Advanced', description: 'Complex grid layout', expectedOutput: 'grid-template-areas defined' },
        { title: 'Clip Path', description: 'Create custom shape', expectedOutput: 'clip-path: polygon();' },
        { title: 'Filter Effects', description: 'Apply blur filter', expectedOutput: 'filter: blur(5px);' },
        { title: 'Backdrop Filter', description: 'Blur background', expectedOutput: 'backdrop-filter: blur(10px);' },
        { title: 'Scroll Snap', description: 'Implement scroll snapping', expectedOutput: 'scroll-snap-type: y mandatory;' },
        { title: 'Sticky Position', description: 'Create sticky header', expectedOutput: 'position: sticky; top: 0;' },
        { title: 'CSS Shapes', description: 'Text wrap around shape', expectedOutput: 'shape-outside: circle();' },
        { title: 'Mix Blend Mode', description: 'Blend elements', expectedOutput: 'mix-blend-mode: multiply;' },
        { title: 'CSS Counter', description: 'Auto-numbering with counter', expectedOutput: 'counter-increment: section;' },
        { title: 'Aspect Ratio', description: 'Maintain aspect ratio', expectedOutput: 'aspect-ratio: 16/9;' },
        { title: 'Container Query', description: 'Use container queries', expectedOutput: '@container (min-width: 400px)' },
        { title: 'Subgrid', description: 'Implement subgrid', expectedOutput: 'grid-template-columns: subgrid;' },
        { title: 'Custom Scrollbar', description: 'Style scrollbar', expectedOutput: '::-webkit-scrollbar styled' },
        { title: 'Mask Image', description: 'Apply image mask', expectedOutput: 'mask-image: url();' },
        { title: 'Writing Mode', description: 'Vertical text layout', expectedOutput: 'writing-mode: vertical-rl;' },
        { title: 'Perspective', description: '3D transform perspective', expectedOutput: 'perspective: 1000px;' },
        { title: 'Will Change', description: 'Optimize animations', expectedOutput: 'will-change: transform;' },
        { title: 'CSS Houdini', description: 'Use CSS Paint API', expectedOutput: 'Custom paint worklet' },
      ],
      extreme: [
        { title: 'Complex Layout', description: 'Build masonry layout', expectedOutput: 'Masonry grid created' },
        { title: 'Dark Mode Toggle', description: 'Implement theme switcher', expectedOutput: 'Theme toggle working' },
        { title: 'Parallax Scrolling', description: 'Create parallax effect', expectedOutput: 'Parallax implemented' },
        { title: 'Morphing Shapes', description: 'Animate shape morphing', expectedOutput: 'Shapes morphing' },
        { title: 'Glassmorphism', description: 'Create glass effect', expectedOutput: 'Glass effect applied' },
        { title: 'Neumorphism', description: 'Design neumorphic UI', expectedOutput: 'Neumorphic design' },
        { title: 'SVG Animation', description: 'Animate SVG with CSS', expectedOutput: 'SVG animated' },
        { title: 'Page Transitions', description: 'Smooth page transitions', expectedOutput: 'Transitions working' },
        { title: 'Loading Spinner', description: 'Pure CSS spinner', expectedOutput: 'Spinner created' },
        { title: 'Hamburger Menu', description: 'Animated hamburger icon', expectedOutput: 'Menu animates' },
        { title: 'Card Flip Effect', description: '3D card flip animation', expectedOutput: 'Card flips' },
        { title: 'Accordion Menu', description: 'CSS-only accordion', expectedOutput: 'Accordion works' },
        { title: 'Tooltip System', description: 'Custom tooltips', expectedOutput: 'Tooltips showing' },
        { title: 'Progress Bar', description: 'Animated progress bar', expectedOutput: 'Progress animates' },
        { title: 'Skeleton Loading', description: 'Loading skeleton screen', expectedOutput: 'Skeleton created' },
        { title: 'Infinite Scroll', description: 'Infinite scroll indicator', expectedOutput: 'Scroll indicator' },
        { title: 'Particle Effect', description: 'CSS particle animation', expectedOutput: 'Particles animated' },
        { title: 'Typewriter Effect', description: 'Typing animation', expectedOutput: 'Text types out' },
        { title: 'Waterfall Layout', description: 'Pinterest-style layout', expectedOutput: 'Waterfall created' },
        { title: 'Full Page Scroll', description: 'Section snapping scroll', expectedOutput: 'Full page scroll' },
      ],
    };
    return cssTemplates[level];
  }
  
  const templates = {
    easy: [
      { title: 'Hello World', description: 'Write a program to print "Hello World"', expectedOutput: 'Hello World' },
      { title: 'Sum of Two Numbers', description: 'Write a program to find the sum of two numbers (5 and 10)', expectedOutput: '15' },
      { title: 'Even or Odd', description: 'Write a program to check if a number (7) is even or odd', expectedOutput: 'Odd' },
      { title: 'Maximum of Two', description: 'Find the maximum of two numbers (15 and 23)', expectedOutput: '23' },
      { title: 'Area of Rectangle', description: 'Calculate area of rectangle with length=5 and width=3', expectedOutput: '15' },
      { title: 'Swap Variables', description: 'Swap two variables a=10 and b=20', expectedOutput: 'a=20, b=10' },
      { title: 'Positive or Negative', description: 'Check if number -5 is positive or negative', expectedOutput: 'Negative' },
      { title: 'Simple Interest', description: 'Calculate SI with P=1000, R=5, T=2', expectedOutput: '100' },
      { title: 'Celsius to Fahrenheit', description: 'Convert 37°C to Fahrenheit', expectedOutput: '98.6' },
      { title: 'Average of Three', description: 'Find average of 10, 20, 30', expectedOutput: '20' },
      { title: 'Square of Number', description: 'Calculate square of 7', expectedOutput: '49' },
      { title: 'Perimeter of Circle', description: 'Find perimeter with radius=7', expectedOutput: '44' },
      { title: 'Multiply Two Numbers', description: 'Multiply 8 and 6', expectedOutput: '48' },
      { title: 'Divide Two Numbers', description: 'Divide 50 by 5', expectedOutput: '10' },
      { title: 'Remainder', description: 'Find remainder of 17 divided by 5', expectedOutput: '2' },
      { title: 'Cube of Number', description: 'Find cube of 4', expectedOutput: '64' },
      { title: 'Compare Numbers', description: 'Check if 15 equals 15', expectedOutput: 'Equal' },
      { title: 'Sum of First 5', description: 'Find sum of first 5 natural numbers', expectedOutput: '15' },
      { title: 'Ascii Value', description: 'Print ASCII value of character A', expectedOutput: '65' },
      { title: 'Absolute Value', description: 'Find absolute value of -42', expectedOutput: '42' },
    ],
    medium: [
      { title: 'Factorial', description: 'Calculate factorial of 5', expectedOutput: '120' },
      { title: 'Fibonacci Series', description: 'Print first 7 Fibonacci numbers', expectedOutput: '0 1 1 2 3 5 8' },
      { title: 'Prime Number', description: 'Check if 17 is prime', expectedOutput: 'Prime' },
      { title: 'Reverse Number', description: 'Reverse the number 1234', expectedOutput: '4321' },
      { title: 'Palindrome', description: 'Check if 121 is palindrome', expectedOutput: 'Palindrome' },
      { title: 'Armstrong Number', description: 'Check if 153 is Armstrong', expectedOutput: 'Armstrong' },
      { title: 'Sum of Digits', description: 'Find sum of digits of 1234', expectedOutput: '10' },
      { title: 'LCM of Two', description: 'Find LCM of 12 and 18', expectedOutput: '36' },
      { title: 'GCD of Two', description: 'Find GCD of 24 and 36', expectedOutput: '12' },
      { title: 'Binary to Decimal', description: 'Convert binary 1010 to decimal', expectedOutput: '10' },
      { title: 'Decimal to Binary', description: 'Convert decimal 10 to binary', expectedOutput: '1010' },
      { title: 'Power Function', description: 'Calculate 2 raised to power 5', expectedOutput: '32' },
      { title: 'Pattern Printing', description: 'Print pyramid pattern of 5 rows', expectedOutput: 'Pattern printed' },
      { title: 'Sum of Array', description: 'Sum array [1,2,3,4,5]', expectedOutput: '15' },
      { title: 'Linear Search', description: 'Find 4 in array [1,2,3,4,5]', expectedOutput: 'Found at index 3' },
      { title: 'Count Vowels', description: 'Count vowels in "programming"', expectedOutput: '3' },
      { title: 'String Reverse', description: 'Reverse string "hello"', expectedOutput: 'olleh' },
      { title: 'Largest in Array', description: 'Find largest in [3,7,2,9,1]', expectedOutput: '9' },
      { title: 'Frequency Counter', description: 'Count frequency of 2 in [2,3,2,1,2]', expectedOutput: '3' },
      { title: 'Remove Duplicates', description: 'Remove duplicates from [1,2,2,3,3]', expectedOutput: '[1,2,3]' },
    ],
    hard: [
      { title: 'Binary Search', description: 'Implement binary search for 5 in sorted array', expectedOutput: 'Found' },
      { title: 'Bubble Sort', description: 'Sort array [5,2,8,1,9] using bubble sort', expectedOutput: '[1,2,5,8,9]' },
      { title: 'Selection Sort', description: 'Sort array using selection sort', expectedOutput: 'Sorted array' },
      { title: 'Insertion Sort', description: 'Sort array using insertion sort', expectedOutput: 'Sorted array' },
      { title: 'Merge Sort', description: 'Implement merge sort algorithm', expectedOutput: 'Sorted array' },
      { title: 'Quick Sort', description: 'Implement quick sort algorithm', expectedOutput: 'Sorted array' },
      { title: 'Matrix Addition', description: 'Add two 2x2 matrices', expectedOutput: 'Result matrix' },
      { title: 'Matrix Multiplication', description: 'Multiply two 2x2 matrices', expectedOutput: 'Result matrix' },
      { title: 'Linked List', description: 'Create and traverse linked list', expectedOutput: 'List traversed' },
      { title: 'Stack Implementation', description: 'Implement stack with push/pop', expectedOutput: 'Stack operations done' },
      { title: 'Queue Implementation', description: 'Implement queue with enqueue/dequeue', expectedOutput: 'Queue operations done' },
      { title: 'Tree Traversal', description: 'Implement inorder traversal', expectedOutput: 'Traversal complete' },
      { title: 'Recursion Tower', description: 'Solve Tower of Hanoi for n=3', expectedOutput: '7 moves' },
      { title: 'String Permutations', description: 'Generate permutations of "abc"', expectedOutput: '6 permutations' },
      { title: 'Subset Sum', description: 'Find if subset sum exists', expectedOutput: 'Yes/No' },
      { title: '0/1 Knapsack', description: 'Solve knapsack problem', expectedOutput: 'Maximum value' },
      { title: 'Longest Subsequence', description: 'Find LCS of two strings', expectedOutput: 'Length of LCS' },
      { title: 'Graph DFS', description: 'Implement depth-first search', expectedOutput: 'DFS traversal' },
      { title: 'Graph BFS', description: 'Implement breadth-first search', expectedOutput: 'BFS traversal' },
      { title: 'Dijkstra Algorithm', description: 'Find shortest path using Dijkstra', expectedOutput: 'Shortest path found' },
    ],
    extreme: [
      { title: 'N-Queens Problem', description: 'Solve N-Queens for n=8', expectedOutput: 'All solutions found' },
      { title: 'Sudoku Solver', description: 'Solve 9x9 Sudoku puzzle', expectedOutput: 'Puzzle solved' },
      { title: 'AVL Tree', description: 'Implement self-balancing AVL tree', expectedOutput: 'Tree balanced' },
      { title: 'Red-Black Tree', description: 'Implement Red-Black tree', expectedOutput: 'Tree operations done' },
      { title: 'Trie Data Structure', description: 'Implement Trie with insert/search', expectedOutput: 'Trie implemented' },
      { title: 'Segment Tree', description: 'Build segment tree for range queries', expectedOutput: 'Query results' },
      { title: 'Fenwick Tree', description: 'Implement Binary Indexed Tree', expectedOutput: 'BIT operations done' },
      { title: 'Bellman-Ford', description: 'Detect negative cycles in graph', expectedOutput: 'Cycle detection' },
      { title: 'Floyd-Warshall', description: 'Find all-pairs shortest paths', expectedOutput: 'All paths found' },
      { title: 'Kruskal Algorithm', description: 'Find MST using Kruskal', expectedOutput: 'MST weight calculated' },
      { title: 'Prim Algorithm', description: 'Find MST using Prim', expectedOutput: 'MST constructed' },
      { title: 'Topological Sort', description: 'Sort DAG topologically', expectedOutput: 'Sorted order' },
      { title: 'String Matching', description: 'Implement KMP algorithm', expectedOutput: 'Pattern found' },
      { title: 'Rabin-Karp', description: 'Implement Rabin-Karp matching', expectedOutput: 'Matches found' },
      { title: 'Huffman Coding', description: 'Implement Huffman compression', expectedOutput: 'Encoded string' },
      { title: 'LRU Cache', description: 'Implement LRU cache mechanism', expectedOutput: 'Cache operations' },
      { title: 'Expression Parser', description: 'Parse and evaluate expressions', expectedOutput: 'Expression value' },
      { title: 'Convex Hull', description: 'Find convex hull of points', expectedOutput: 'Hull vertices' },
      { title: 'Maximum Flow', description: 'Implement Ford-Fulkerson', expectedOutput: 'Maximum flow value' },
      { title: 'Travelling Salesman', description: 'Solve TSP using DP', expectedOutput: 'Minimum cost' },
    ],
  };

  return templates[level];
};

export const problemsData: ProblemsDatabase = {
  'C': {
    easy: generateProblems('C', 'easy'),
    medium: generateProblems('C', 'medium'),
    hard: generateProblems('C', 'hard'),
    extreme: generateProblems('C', 'extreme'),
  },
  'C+': {
    easy: generateProblems('C+', 'easy'),
    medium: generateProblems('C+', 'medium'),
    hard: generateProblems('C+', 'hard'),
    extreme: generateProblems('C+', 'extreme'),
  },
  'C++': {
    easy: generateProblems('C++', 'easy'),
    medium: generateProblems('C++', 'medium'),
    hard: generateProblems('C++', 'hard'),
    extreme: generateProblems('C++', 'extreme'),
  },
  'Java': {
    easy: generateProblems('Java', 'easy'),
    medium: generateProblems('Java', 'medium'),
    hard: generateProblems('Java', 'hard'),
    extreme: generateProblems('Java', 'extreme'),
  },
  'JavaScript': {
    easy: generateProblems('JavaScript', 'easy'),
    medium: generateProblems('JavaScript', 'medium'),
    hard: generateProblems('JavaScript', 'hard'),
    extreme: generateProblems('JavaScript', 'extreme'),
  },
  'HTML': {
    easy: generateProblems('HTML', 'easy'),
    medium: generateProblems('HTML', 'medium'),
    hard: generateProblems('HTML', 'hard'),
    extreme: generateProblems('HTML', 'extreme'),
  },
  'PHP': {
    easy: generateProblems('PHP', 'easy'),
    medium: generateProblems('PHP', 'medium'),
    hard: generateProblems('PHP', 'hard'),
    extreme: generateProblems('PHP', 'extreme'),
  },
  'Data Structure': {
    easy: generateProblems('Data Structure', 'easy'),
    medium: generateProblems('Data Structure', 'medium'),
    hard: generateProblems('Data Structure', 'hard'),
    extreme: generateProblems('Data Structure', 'extreme'),
  },
  'ML': {
    easy: generateProblems('ML', 'easy'),
    medium: generateProblems('ML', 'medium'),
    hard: generateProblems('ML', 'hard'),
    extreme: generateProblems('ML', 'extreme'),
  },
  'Python': {
    easy: generateProblems('Python', 'easy'),
    medium: generateProblems('Python', 'medium'),
    hard: generateProblems('Python', 'hard'),
    extreme: generateProblems('Python', 'extreme'),
  },
  'MySQL': {
    easy: generateProblems('MySQL', 'easy'),
    medium: generateProblems('MySQL', 'medium'),
    hard: generateProblems('MySQL', 'hard'),
    extreme: generateProblems('MySQL', 'extreme'),
  },
  'CSS': {
    easy: generateProblems('CSS', 'easy'),
    medium: generateProblems('CSS', 'medium'),
    hard: generateProblems('CSS', 'hard'),
    extreme: generateProblems('CSS', 'extreme'),
  },
};
